#[allow(warnings)]
mod ffi;

pub use ffi::{
    astc_enc_settings, //
    bc6h_enc_settings,
    bc7_enc_settings,
    etc_enc_settings,
    rgba_surface,
    CompressBlocksASTC,
    CompressBlocksBC1,
    CompressBlocksBC3,
    CompressBlocksBC6H,
    CompressBlocksBC7,
    CompressBlocksETC1,
    GetProfile_alpha_basic,
    GetProfile_alpha_fast,
    GetProfile_alpha_slow,
    GetProfile_alpha_ultrafast,
    GetProfile_alpha_veryfast,
    GetProfile_astc_alpha_fast,
    GetProfile_astc_alpha_slow,
    GetProfile_astc_fast,
    GetProfile_basic,
    GetProfile_bc6h_basic,
    GetProfile_bc6h_fast,
    GetProfile_bc6h_slow,
    GetProfile_bc6h_veryfast,
    GetProfile_bc6h_veryslow,
    GetProfile_etc_slow,
    GetProfile_fast,
    GetProfile_slow,
    GetProfile_ultrafast,
    GetProfile_veryfast,
    ReplicateBorders,
};
